kind: pipeline
type: exec
name: linux-amd64

platform:
  arch: amd64
  os: linux

steps:
- name: publish
  commands:
  - echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
  - VERSION=20 IMAGE_TAG=20-linux-amd64 ./build.sh build
  environment:
    DRYCC_REGISTRY:
      from_secret: drycc_registry
    DOCKER_USERNAME:
      from_secret: docker_username
    DOCKER_PASSWORD:
      from_secret: docker_password
  when:
    event:
    - push
    - tag

---
kind: pipeline
type: exec
name: linux-arm64

platform:
  arch: arm64
  os: linux

steps:
- name: publish
  commands:
  - echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
  - VERSION=20 IMAGE_TAG=20-linux-arm64 ./build.sh build
  environment:
    DRYCC_REGISTRY:
      from_secret: drycc_registry
    DOCKER_USERNAME:
      from_secret: docker_username
    DOCKER_PASSWORD:
      from_secret: docker_password
  when:
    event:
    - push
    - tag

---
kind: pipeline
type: docker
name: manifest

steps:
- name: manifest
  image: docker.io/library/alpine
  commands:
  - sed -i "s/docker.io/$${DRYCC_REGISTRY}/g" .drone/manifest-20.tmpl
  environment:
    DRYCC_REGISTRY:
      from_secret: drycc_registry

- name: publish-20
  image: plugins/manifest
  settings:
    spec: .drone/manifest-20.tmpl
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  environment:
    DEV_REGISTRY:
      from_secret: dev_registry

trigger:
  event:
  - push
  - tag

depends_on:
- linux-amd64
- linux-arm64
