kind: pipeline
type: docker
name: linux-amd64

platform:
  arch: amd64
  os: linux

steps:
- name: publish
  image: docker.io/library/docker:dind
  privileged: true
  commands:
  - nohup dockerd &
  - apk add make bash curl
  - echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
  - STACK=18 VERSION=18-linux-amd64 ./build.sh build
  - STACK=20 VERSION=20-linux-amd64 ./build.sh build
  environment:
    DRYCC_REGISTRY:
      from_secret: drycc_registry
    DOCKER_USERNAME:
      from_secret: docker_username
    DOCKER_PASSWORD:
      from_secret: docker_password
  when:
    event:
    - push
    - tag

---
kind: pipeline
type: docker
name: linux-arm64

platform:
  arch: arm64
  os: linux

steps:
- name: publish
  image: docker.io/library/docker:dind
  privileged: true
  commands:
  - nohup dockerd &
  - apk add make bash curl
  - echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin
  - STACK=18 VERSION=18-linux-arm64 ./build.sh build
  - STACK=20 VERSION=20-linux-arm64 ./build.sh build
  environment:
    DRYCC_REGISTRY:
      from_secret: drycc_registry
    DOCKER_USERNAME:
      from_secret: docker_username
    DOCKER_PASSWORD:
      from_secret: docker_password
  when:
    event:
    - push
    - tag

---
kind: pipeline
type: docker
name: manifest

steps:
- name: manifest
  image: docker.io/library/alpine
  commands:
  - sed -i "s/docker.io/$${DRYCC_REGISTRY}/g" .drone/manifest-18.tmpl
  - sed -i "s/docker.io/$${DRYCC_REGISTRY}/g" .drone/manifest-18-build.tmpl
  - sed -i "s/docker.io/$${DRYCC_REGISTRY}/g" .drone/manifest-20.tmpl
  - sed -i "s/docker.io/$${DRYCC_REGISTRY}/g" .drone/manifest-20-build.tmpl
  environment:
    DRYCC_REGISTRY:
      from_secret: drycc_registry

- name: publish-18
  image: plugins/manifest
  settings:
    spec: .drone/manifest-18.tmpl
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  environment:
    DEV_REGISTRY:
      from_secret: dev_registry

  when:
    event:
    - push
    - tag

- name: publish-18-build
  image: plugins/manifest
  settings:
    spec: .drone/manifest-18-build.tmpl
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  environment:
    DEV_REGISTRY:
      from_secret: dev_registry

  when:
    event:
    - push
    - tag

- name: publish-20
  image: plugins/manifest
  settings:
    spec: .drone/manifest-20.tmpl
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  environment:
    DEV_REGISTRY:
      from_secret: dev_registry

  when:
    event:
    - push
    - tag

- name: publish-20-build
  image: plugins/manifest
  settings:
    spec: .drone/manifest-20-build.tmpl
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  environment:
    DEV_REGISTRY:
      from_secret: dev_registry

  when:
    event:
    - push
    - tag

depends_on:
- linux-amd64
- linux-arm64
